spring:
  cloud:
    vault:
      enabled: true
      uri: http://guam-vault.jon-snow-korea.com:8200
      authentication: TOKEN
      token: "" # env SPRING_CLOUD_VAULT_TOKEN
  r2dbc:
    url: # in vault
    username: # in vault
    password: # in vault
---
spring.config.activate.on-profile: dev

spring.config.import: vault://kv/dev/immigration

---
spring.config.activate.on-profile: prod

spring.config.import: vault://kv/prod/immigration
