### POST_DETAIL - ID: 1

GET {{ base_url }}/posts/188
Content-Type: application/json
X-GATEWAY-USER-ID: 9

### POST_DETAIL - ID: 1

GET {{ base_url }}/posts/
Content-Type: application/json
X-GATEWAY-USER-ID: 9

### GET USER'S POSTS

GET {{ base_url }}/users/1/posts
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### GET USER'S COMMENTS

GET {{ base_url }}/users/3/comments
Content-Type: application/json
X-GATEWAY-USER-ID: 1