### POST_DETAIL - ID: 1

GET {{ base_url }}/posts/188
Content-Type: application/json
X-GATEWAY-USER-ID: 9

### POST_DETAIL - ID: 1

GET {{ base_url }}/posts/search?keyword=허락된건
Content-Type: application/json
X-GATEWAY-USER-ID: 9

### GET USER'S POSTS

GET {{ base_url }}/users/1/posts
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### GET USER'S COMMENTS

GET {{ base_url }}/users/3/comments
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### POST POST_COMMENT
POST localhost:8080/api/v1/posts/284/comments
Content-Type: application/json
X-GATEWAY-USER-ID: 48

{
  "content": "카프카를 테스트 하고 있습니다 ^^"
}

### 신고
POST localhost:8080/api/v1/posts/report
Content-Type: application/json
X-GATEWAY-USER-ID: 48

{
  "postId": 111,
  "reason": "신고신고"
}

### 신고
POST localhost:8080/api/v1/comments/report
Content-Type: application/json
X-GATEWAY-USER-ID: 48

{
  "commentId": 111,
  "reason": "신고신고"
}

