apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: community-api
spec:
  hosts:
    - "guam-community.wafflestudio.com"
  gateways:
    - istio-system/waffle-ingressgateway
  http:
    - route:
        - destination:
            host: community-api
