GET {{ base_url }}/auth?token={{ accessToken }}
Content-Type: application/json

### USER_ME

GET {{ base_url }}/users/me
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### USER_DETAIL - ID: 1

GET {{ base_url }}/users/1
Content-Type: application/json
X-GATEWAY-USER-ID: 2

### POST_DETAIL - ID: 1

GET {{ base_url }}/posts/188
Content-Type: application/json
X-GATEWAY-USER-ID: 9

### UPDATE_USER - ID: 1

PATCH  {{ base_url }}/users/1
Content-Type: application/json
X-GATEWAY-USER-ID: 1

{
  "nickname": "steve"
}

### ADD STACK - ID: 1

POST {{ base_url }}/users/1/stack
Content-Type: application/json
X-GATEWAY-USER-ID: 1

{
  "name": "스프링"
}

### DELETE STACK - ID: 1

DELETE {{ base_url }}/users/1/stack?name=스프링
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### GET USER'S POSTS

GET {{ base_url }}/users/1/posts
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### GET USER'S COMMENTS

GET {{ base_url }}/users/3/comments
Content-Type: application/json
X-GATEWAY-USER-ID: 1

### GET USER'S COMMENTS

POST {{ base_url }}/posts/190/comments/224/likes
Content-Type: application/json
X-GATEWAY-USER-ID: 1