apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
spec:
  selector:
    matchLabels:
      app: gateway-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: pfcjeong/guam-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              memory: 384Mi