apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-api
spec:
  hosts:
    - "guam.jon-snow-korea.com"
  gateways:
    - istio-system/waffle-ingressgateway
  http:
    - route:
        - destination:
            host: gateway-api
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api
spec:
  selector:
    app: gateway-api
  ports:
    - name: http
      port: 80
      targetPort: 8080