spring:
  profiles:
    active: dev
---
spring.config.activate.on-profile: dev

spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 5s
      enabled: true
      routes:
        - id: community_route
          uri: http://guam-community.jon-snow-korea.com
          predicates:
            - Path=/community/**
          filters:
            - RewritePath=/community(?<segment>/?.*), $\{segment}
            - Guam