spring:
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: true

spring.config.import:
  - classpath:application-aws.yaml
  - classpath:application-db.yaml
  - classpath:application-slack.yaml
  - classpath:application-vault.yaml