apiVersion: batch/v1
kind: Job
metadata:
  name: post-like-loader
spec:
  template:
    spec:
      containers:
        - name: post-like-loader
          image: kangjirm/guam-favorite-batch
          args: ["--job.name=LOAD_POST_LIKE_RANK"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-comment-like-loader
spec:
  template:
    spec:
      containers:
        - name: post-comment-like-loader
          image: kangjirm/guam-favorite-batch
          args: ["--job.name=LOAD_POST_COMMENT_LIKE_RANK"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-scrap-loader
spec:
  template:
    spec:
      containers:
        - name: post-scrap-loader
          image: kangjirm/guam-favorite-batch
          args: ["--job.name=LOAD_POST_SCRAP_RANK"]
      restartPolicy: Never
---
