apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: favorite-api
spec:
  hosts:
    - "guam-favorite-api.wafflestudio.com"
  gateways:
    - istio-ingress/waffle-ingressgateway
  http:
    - route:
        - destination:
            host: favorite-api
