spring:
  jpa:
    show-sql: true
  batch:
    job:
      names: ${job.name:NONE}
  config:
    import: application-service.yaml

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false
