spring:
  datasource:
    url: ""
    username: ""
    password: ""
  batch:
    job:
      names: ${job.name:NONE}
      chunkSize: ${job.chunkSize:100}
  config:
    import: application-service.yaml
---

spring:
  config:
    activate:
      on-profile: dev
