apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer
spec:
  selector:
    matchLabels:
      app: notification-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      containers:
        - name: notification-consumer
          image: kangjirm/guam-notification-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guam-secret
                  key: vaulttoken
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              memory: 512Mi
