spring:
  cloud:
    vault:
      enabled: true
      uri: http://guam-vault.jon-snow-korea.com:8200
      authentication: TOKEN
      token: s.53RQSdXUr77gqzLyuWRaY092
cloud:
  aws:
    credentials:
      accessKey: "" # vault
      secretKey: "" # vault
      instanceProfile: false
    s3:
      bucket: guam
    region:
      static: ap-northeast-2
    stack:
      auto: false
guam:
  services:
    user:
      baseUrl: http://guam-user.jon-snow-korea.com
    favorite:
      baseUrl: http://guam-favorite.jon-snow-korea.com
    notification:
      baseUrl: http://guam-user.jon-snow-korea.com
---
spring.config.activate.on-profile: dev

spring.config.import: vault://kv/dev/community

---
spring.config.activate.on-profile: prod

spring.config.import: vault://kv/prod/community
