spring:
  cloud:
    vault:
      enabled: true
      uri: http://guam-vault.jon-snow-korea.com:8200
      authentication: TOKEN
      token: s.53RQSdXUr77gqzLyuWRaY092
  r2dbc:
    url: # in vault
    username: # in vault
    password: # in vault

letter:
  aws:
    s3:
      accessKey: "" # vault
      secretKey: "" # vault
      bucket: "" # vault
      region: "" # vault
---
spring.config.activate.on-profile: dev

spring.config.import: vault://kv/dev/letter

---
spring.config.activate.on-profile: prod

spring.config.import: vault://kv/prod/letter