apiVersion: apps/v1
kind: Deployment
metadata:
  name: letter-api
spec:
  selector:
    matchLabels:
      app: letter-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: letter-api
    spec:
      containers:
        - name: letter-api
          image: pfcjeong/guam-letter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guam-secret
                  key: vaulttoken
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              memory: 384Mi
