apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: letter-api
spec:
  hosts:
    - "guam-letter.jon-snow-korea.com"
  gateways:
    - istio-system/waffle-ingressgateway
  http:
    - route:
        - destination:
            host: letter-api
---
apiVersion: v1
kind: Service
metadata:
  name: letter-api
spec:
  selector:
    app: letter-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: guam-secret
type: Opaque
stringData:
  vaulttoken: s.5T8EEGtEdcdgJNj7Z6qE8UIR
  slacktoken: xoxb-6971793892-2926327856006-9vsOkKbYNVaJ78sgdvQpWudD
