apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  master.conf: |
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    maxclients 1000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data
  slave.conf: |
    slaveof redis-ss-0.redis-ss.redis 6379
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    maxclients 1000
    timeout 300
    dir /data
