name: Deploy With Gradle

on:
  push:
    branches:
      - develop

jobs:
  build_and_push_container:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Login to Docker registry first
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Code
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DCR_NAME }} .
        # NO Tag Versioning Now

      - name: Push Docker Image
        run: docker push ${{ secrets.DCR_NAME }}


