apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-api
    spec:
      # TODO 공통 부분 처리 못할까?
      containers:
        - name: user-api
          image: pfcjeong/guam-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guam-secret
                  key: vaulttoken
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              memory: 512Mi
        - name: notification-consumer
          image: kangjirm/guam-notification-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guam-secret
                  key: vaulttoken
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
          resources:
            requests:
              cpu: 128m
              memory: 256Mi
            limits:
              memory: 512Mi
